begin;

create table public.groups (
  id text primary key,
  name text not null,
  type text not null check (type in ('일반', '새순', '새내기')),
  naming_rule text not null default '',
  active boolean not null default true,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.members (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 50),
  phone text not null default '',
  status text not null check (status in ('정착', '신규자', '비활성')),
  group_id text not null references public.groups(id) on update cascade on delete restrict,
  registered_on date,
  assigned_on date,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_users (
  id text primary key,
  name text not null,
  role text not null check (role in ('순장', '최고권한')),
  group_id text references public.groups(id) on update cascade on delete restrict,
  member_id bigint references public.members(id) on update cascade on delete set null,
  access_code text not null unique check (char_length(access_code) between 6 and 100),
  active boolean not null default true,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((role = '최고권한' and group_id is null) or (role = '순장' and group_id is not null))
);

create table public.attendance (
  attendance_date date not null,
  member_id bigint not null references public.members(id) on update cascade on delete restrict,
  group_id text not null references public.groups(id) on update cascade on delete restrict,
  worship text not null default '' check (worship in ('', '출석', '결석', '온라인')),
  cell text not null default '' check (cell in ('', '참석', '불참')),
  note text not null default '' check (char_length(note) <= 500),
  checked_by text not null default '',
  recorded_at timestamptz not null default now(),
  primary key (attendance_date, member_id)
);

create index members_group_id_idx on public.members(group_id);
create index members_status_idx on public.members(status);
create index app_users_active_code_idx on public.app_users(access_code) where active;
create index app_users_group_id_idx on public.app_users(group_id) where role = '순장';
create index attendance_member_date_idx on public.attendance(member_id, attendance_date desc);
create index attendance_group_date_idx on public.attendance(group_id, attendance_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger groups_set_updated_at
before update on public.groups
for each row execute function public.set_updated_at();

create trigger members_set_updated_at
before update on public.members
for each row execute function public.set_updated_at();

create trigger app_users_set_updated_at
before update on public.app_users
for each row execute function public.set_updated_at();

alter table public.groups enable row level security;
alter table public.members enable row level security;
alter table public.app_users enable row level security;
alter table public.attendance enable row level security;

revoke all on public.groups from anon, authenticated;
revoke all on public.members from anon, authenticated;
revoke all on public.app_users from anon, authenticated;
revoke all on public.attendance from anon, authenticated;
revoke all on function public.set_updated_at() from public;

commit;
